<?php

function customcut_register_assets()
{
  // use for scripts and styles scoped to just the block editor scoped 
  // Load asset metadata generated by @wordpress/scripts for the global editor bundle.
  $editorAssets = include get_theme_file_path('/build/index.asset.php');

  wp_enqueue_script(
    'customcut-editor',
    get_theme_file_uri('/build/index.js'),
    $editorAssets['dependencies'] ?? [],
    $editorAssets['version'] ?? null
  );

  wp_enqueue_style(
    'customcut-editor',
    get_theme_file_uri('/build/index.css'),
    [],
    $editorAssets['version'] ?? null
  );
}
add_action( 'enqueue_block_editor_assets', 'customcut_register_assets' );
